'use strict'
const fs = require('fs')
const lines = []
lines.push('-- Bite Me Baby Migration 070: TEN-03 Enforce NOT NULL on catalog tenant_id')
lines.push('-- SET NOT NULL on all 7 catalog tables after backfill verifies 0 nulls remain')
lines.push('BEGIN;')
lines.push('DO $$ DECLARE v_p int; v_c int; v_s int; BEGIN SELECT count(*) INTO v_p FROM public.products WHERE tenant_id IS NULL; SELECT count(*) INTO v_c FROM public.product_categories WHERE tenant_id IS NULL; SELECT count(*) INTO v_s FROM public.menu_sections WHERE tenant_id IS NULL; IF v_p > 0 OR v_c > 0 OR v_s > 0 THEN RAISE EXCEPTION \'ERR_ENFORCE_NULLS: products=%, categories=%, sections=% still have null.\'; END IF; END $$;')
lines.push('')
lines.push('-- Also verify newly created tables have no null tenant_id')
lines.push('DO $$ DECLARE v_ag int; v_a int; v_pag int; BEGIN SELECT count(*) INTO v_ag FROM public.addon_groups WHERE tenant_id IS NULL; SELECT count(*) INTO v_a FROM public.addons WHERE tenant_id IS NULL; SELECT count(*) INTO v_pag FROM public.product_addon_groups WHERE tenant_id IS NULL; IF v_ag > 0 OR v_a > 0 OR v_pag > 0 THEN RAISE EXCEPTION \'ERR_ENFORCE_NULLS: addon_groups=%, addons=%, product_addon_groups=% still have null.\'; END IF; END $$;')
lines.push('')
lines.push('ALTER TABLE public.products ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('ALTER TABLE public.product_categories ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('ALTER TABLE public.menu_sections ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('ALTER TABLE public.addon_groups ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('ALTER TABLE public.addons ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('ALTER TABLE public.product_addon_groups ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('ALTER TABLE public.menu_schedule ALTER COLUMN tenant_id SET NOT NULL;')
lines.push('COMMIT;')
fs.writeFileSync('./supabase/migrations/070_enforce_catalog_not_null.sql', lines.join('\n'), 'utf-8')
console.log('Migration-070 regenerated:', lines.length, 'lines')
