// One-off: self-host Google Fonts (Nunito + Quicksand) to kill the
// render-blocking third-party requests flagged by Lighthouse.
// Downloads every @font-face woff2 (incl. thai subset) into public/fonts/
// and rewrites a local public/fonts/fonts.css with font-display: swap.
'use strict'
const fs = require('fs')
const path = require('path')
const OUT = path.join('public', 'fonts')
fs.mkdirSync(OUT, { recursive: true })
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Quicksand:wght@400;600;700&display=swap'
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
;(async () => {
  const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } })
  if (!res.ok) { console.log('XMARK css http', res.status); process.exit(1) }
  const css = await res.text()
  // split into @font-face blocks, download each url, rewrite css
  const blocks = css.match(/@font-face\s*{[^}]+}/g) || []
  let i = 0
  const out = []
  for (const b of blocks) {
    const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1] || 'font'
    const w = (b.match(/font-weight:\s*([0-9 ]+);/) || [])[1] || '400'
    const st = (b.match(/font-style:\s*(\w+)/) || [])[1] || 'normal'
    const ur = (b.match(/unicode-range:\s*([^;]+);/) || [])[1] || ''
    const url = (b.match(/url\((https:[^)]+\.woff2)\)/) || [])[1]
    if (!url) { out.push(b); continue }
    const sub = /U\+0E01/.test(ur) ? 'thai' : /U\+0100/.test(ur) ? 'latin-ext' : /U\+0131/.test(ur) ? 'latin' : 's' + i
    const fname = `${fam.toLowerCase().replace(/\s+/g, '-')}-${w.replace(/\s+/g, '_')}-${st}-${sub}.woff2`
    const r2 = await fetch(url, { headers: { 'User-Agent': UA } })
    if (!r2.ok) { console.log('XMARK font http', r2.status, url); process.exit(1) }
    fs.writeFileSync(path.join(OUT, fname), Buffer.from(await r2.arrayBuffer()))
    out.push(b.replace(url, '/fonts/' + fname))
    i++
  }
  const cssOut =
    '/* Self-hosted Google Fonts (Nunito + Quicksand) — generated by scripts/fetchFonts.cjs */\n' +
    out.join('\n').replace(/font-display:\s*swap;/g, 'font-display: swap;') + '\n'
  fs.writeFileSync(path.join(OUT, 'fonts.css'), cssOut)
  console.log('OK fonts downloaded:', i, '-> public/fonts')
})().catch((e) => { console.log('XMARK', String(e).slice(0, 400)); process.exit(1) })
